std::vector<std::string> _defaultKeys =
{
    "                                                                                ",
    "; Keyboard input, (maybe other devices in the future), configuration file       ",
    "; This file dictates how the entire software is controlled and how the help     ",
    "; menu is displayed. If this file is changed, the emulator has to be restarted  ",
    "; Most keys are editable, (in the INI file, not the help screen)                ",
    "                                                                                ",
    "[Monitor]                ; case sensitive                                       ",
    "Edit         = ENTER     ; toggles edit mode or uploads vasm/gt1 files          ",
    "RAM_Mode     = R         ; toggles between RAM and ROM modes                    ",
    "Execute      = CTRL+F5   ; executes whatever code is present at the load address",
    "Left         = LEFT      ; moves cursor left with wrap around                   ",
    "Right        = RIGHT     ; moves cursor right with wrap around                  ",
    "Up           = UP        ; moves cursor up with wrap around                     ",
    "Down         = DOWN      ; moves cursor down with wrap around                   ",
    "PageUp       = PAGEUP    ; scrolls cursor or browser one page up at a time      ",
    "PageDown     = PAGEDOWN  ; scrolls cursor or browser one page down at a time    ",
    "Hex_Mode     = CTRL+F9   ; switches to Hex mode from any other mode             ",
    "                                                                                ",
    "[Browser]                ; case sensitive                                       ",
    "Load         = L         ; toggles between monitor mode and browser mode        ",
    "                                                                                ",
    "[Emulator]               ; case sensitive                                       ",
    "Help         = CTRL+H    ; toggles help screen on and off                       ",
    "Quit         = CTRL+Q    ; instant quit                                         ",
    "Reset        = CTRL+F1   ; instant reset                                        ",
    "ScanlineMode = CTRL+F3   ; toggles scanline modes, Normal, VideoB and VideoBC   ",
    "Speed+       = +         ; increases the emulation speed                        ",
    "Speed-       = -         ; decreases the emulation speed                        ",
    "PS2_KB       = CTRL+F10  ; toggles PS2 Keyboard emulation on and off            ",
    "                                                                                ",
    "[Gigatron]               ; case sensitive                                       ",
    "Giga_Left    = A         ; left input to Gigatron                               ",
    "Giga_Right   = D         ; right input to Gigatron                              ",
    "Giga_Up      = W         ; up input to Gigatron                                 ",
    "Giga_Down    = S         ; down input to Gigatron                               ",
    "Giga_Start   = SPACE     ; start input to Gigatron                              ",
    "Giga_Select  = Z         ; select input to Gigatron                             ",
    "Giga_A       = .         ; A input to Gigatron                                  ",
    "Giga_B       = /         ; B input to Gigatron                                  ",
	"                                                                                ",
	"[Hardware]               ; case sensitive                                       ",
    "Giga         = CTRL+F11  ; toggles Gigatron input between emulator and hardware ",
    "Giga_PS2     = CTRL+F12  ; toggles PS2 keyboard between emulator and hardware   ",
    "Giga_Reset   = ALT+F1    ; resets hardware                                      ",
    "Giga_Execute = ALT+F5    ; uploads and excutes .vasm and .gt1 files to hardware ",
    "                                                                                ",
    "[Debugger]               ; case sensitive                                       ",
    "Debug        = CTRL+F6   ; toggles debugging mode, can be used to pause         ",
    "Step         = CTRL+F7   ; single steps debugger based on a watched variable    ",
    "                         ; by default is videoY which changes once per scanline ",
    "                                                                                "
};