
dasm puzz15.asm -la.lst

# Create puzz15.gcl file
(
echo '{ Generated by: cd asm/15puz && ./make.sh }'

# Hex dump
od -v -A n -t x1 a.out |
 fmt -1 |
  tail +3 |
  awk -v A=1024 '
   NF>0 {
    if(A%16==0)print""
    if(A%256==0)printf"\n*=$%x\n",A
    printf " #$%-2s",$1
    A++}
   END          {print}
  '
) > ../../puzz15.gcl
